- id: "/"
  title: "German Italian Physics Exchange"
  description: "The Italian Association of Physics Students (AISF) and the junge Deutschen Physikalischen Gesellschaft (jDPG) will join for the first year of the German Italian Physics Exchange in Hamburg on November 2017.</p><p>
During the Programme, 40 students will be able to visit some cutting-edge facilities including the Nexperia's Front End Manufacturing, DESY, the labs of the Max-Planck-Instutute for the structure and dynamics of matter, the Center for Free-Electron Laser Science and the Institute of Laserphysics.
Moreover, the participants will be given talks by local professors, researchers and managers.
The event is organized and sponsored by the German Physical Society (DPG)."
  keywords: "jDPG aisf associazione italiana studenti di fisica iaps gipe physics desy hamburg exchange ilp flash"
